### PR TITLE
use cmake generate files from .in template file

### PR DESCRIPTION
**Pull request by da-liii**
Karl, I'am sorry that I haven't cleaned my workspace and tested it yesterday.

This time it should work:

```
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=somewhere
make -j4
make install
```

`./configure` is not needed

### CODE REVIEW

**Comment by KarlHegbloom** [comment]
/home/karlheg/src/TeXmacs/texmacs-git-svn/src/src/Texmacs/Server/tm_debug.cpp: In function ‘string get_system_information()’:
/home/karlheg/src/TeXmacs/texmacs-git-svn/src/src/Texmacs/Server/tm_debug.cpp:31:8: error: ‘BUILD_USER’ was not declared in this scope
     << BUILD_USER << "\n";
        ^
/home/karlheg/src/TeXmacs/texmacs-git-svn/src/src/Texmacs/Server/tm_debug.cpp:33:8: error: ‘BUILD_DATE’ was not declared in this scope
     << BUILD_DATE << "\n";
        ^
/home/karlheg/src/TeXmacs/texmacs-git-svn/src/src/Texmacs/Server/tm_debug.cpp:35:8: error: ‘HOST_OS’ was not declared in this scope
     << HOST_OS << "\n";
        ^
/home/karlheg/src/TeXmacs/texmacs-git-svn/src/src/Texmacs/Server/tm_debug.cpp:37:8: error: ‘HOST_VENDOR’ was not declared in this scope
     << HOST_VENDOR << "\n";
        ^
/home/karlheg/src/TeXmacs/texmacs-git-svn/src/src/Texmacs/Server/tm_debug.cpp:39:8: error: ‘HOST_CPU’ was not declared in this scope
     << HOST_CPU << "\n";
        ^
src/CMakeFiles/texmacs.bin.dir/build.make:5302: recipe for target 'src/CMakeFiles/texmacs.bin.dir/Texmacs/Server/tm_debug.cpp.o' failed
make[2]: **\* [src/CMakeFiles/texmacs.bin.dir/Texmacs/Server/tm_debug.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
CMakeFiles/Makefile2:159: recipe for target 'src/CMakeFiles/texmacs.bin.dir/all' failed
make[1]: **\* [src/CMakeFiles/texmacs.bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2
Exit Status: [2]

**Comment by KarlHegbloom** [comment]
Take a look at my branch called "syrinx-pure-cmake".

 cmake -G ninja -DTEXMACS_GUI=Qt5
 ninja

**Comment by da-liii** [comment]
I works fine using ninja.

**Comment by KarlHegbloom** [comment]
Yes... In the new branch it builds with Qt5 now.

**Comment by da-liii** [comment]
Karl, I'm trying to make TeXmacs work using Guile2.0

I have several free days during this period (just a gap between graduation from school and starting to work as a programmer)

**Comment by KarlHegbloom** [comment]
Good.

**Comment by KarlHegbloom** [comment]
I just committed more cmake changes in the syrinx-pure-cmake branch. Have a
look.
